XDG_DESKTOP_DIR=%h/Desktop
XDG_DOWNLOAD_DIR=%h/Downloads
XDG_PICTURES_DIR=%h/Pictures
XDG_VIDEOS_DIR=%h/Videos
XDG_DOCUMENTS_DIR=%h/Documents
XDG_MUSIC_DIR=%h/Music
XDG_TEMPLATES_DIR=%h/Templates
XDG_PUBLICSHARE_DIR=%h/Public
